// ── book.js — Le Livre du Capitaine Jayden — DATA uniquement (généré depuis livre-jayden.md) ──

const BOOK = {
  title: "Le Livre du Capitaine Jayden",
  cover: "images/jayden_t0c1p1.jpg",
  tomes: [
    {
      id: "t0", title: "Prologue — Le Capitaine du Soir", available: true,
      chapters: [
        { title: "Le Capitaine du Soir", pages: [
          { img: "images/jayden_t0c1p1.jpg",
            text: "Il était une fois un petit garçon très courageux qui s'appelait Jayden. Le jour, Jayden adorait courir, jouer et explorer le monde. Mais la nuit, quand le soleil se couchait et que les étoiles s'allumaient une par une, Jayden devenait quelqu'un de très spécial : il devenait le Capitaine d'un magnifique navire magique, qui voguait sur l'Océan des Rêves.\n\nCe bateau ne ressemblait à aucun autre. Ses voiles étaient blanches et douces comme des nuages de coton, sa coque en bois de santal sentait bon et brillait sous la lune, et il glissait au-dessus des vagues sans jamais faire de bruit.\n\nSur le pont, Jayden avait installé une invention magique de sa fabrication : une grande voile en forme de cerf-volant, reliée à un entonnoir doré. La voile attrapait les petits nuages du soir, tout doux, et l'entonnoir les transformait en une eau pure, fraîche et merveilleusement sucrée. C'était la meilleure eau de tous les océans. Elle faisait pousser de petites fleurs lumineuses autour de la barre, et donnait aux lanternes du bateau une lueur apaisante, couleur de miel.\n\nJayden connaissait le nom de toutes les étoiles du ciel, et il savait parler le langage des vagues. Ce soir-là, la mer était si calme qu'elle ressemblait à un grand miroir d'argent. La brise tiède lui caressait les joues.\n\n— « En avant, mon beau navire ! » murmura le Capitaine Jayden en tournant la barre de bois verni." },
          { img: "images/jayden_t0c1p2.jpg",
            text: "Soudain, il entendit deux petits <em>plouf !</em> juste à côté du navire. Jayden se pencha au-dessus de la rambarde : c'étaient ses deux meilleurs amis de l'océan, deux grands dauphins à la peau argentée, lisse et brillante, qui scintillait sous la lumière des étoiles.\n\n— « Bonsoir, Capitaine Jayden ! » sifflèrent les dauphins en faisant de petits bonds joyeux. « Ce soir, nous te guidons vers l'Île des Rêves ! »\n\nLes dauphins nagèrent devant la proue, traçant sur l'eau un chemin de lumière argentée. Jayden se sentait en parfaite sécurité. Bientôt, l'île apparut à l'horizon : une île magnifique, couverte de grands palmiers qui balançaient leurs feuilles au rythme du vent, comme pour chanter une berceuse. L'air sentait bon la vanille et le sable chaud.\n\nLe navire magique s'arrêta tout doucement dans la petite baie, et l'ancre descendit dans l'eau avec un joli son cristallin, comme une clochette.\n\n— « Mission accomplie », bâilla le Capitaine Jayden.\n\nIl s'installa sur une grosse pile de coussins moelleux, sur le pont de son bateau, bercé par le doux mouvement des vagues et le chant des palmiers. Au-dessus de lui, les étoiles brillaient comme de petites veilleuses, et veillaient sur son sommeil. Les dauphins firent un dernier saut pour lui dire bonne nuit, et tout devint calme.\n\nFerme les yeux toi aussi, Jayden. La mer est calme, les étoiles brillent, et ton bateau magique t'attend pour la grande aventure de demain. Bonne nuit, Capitaine." },
        ]},
      ]
    },
    {
      id: "t1", title: "Tome 1 — Le Fabuleux Secret de l'Île aux Nuages", available: true,
      chapters: [
        { title: "Le Trésor et les Pirates", pages: [
          { img: "images/jayden_t1c1p1.jpg",
            text: "Un soir, alors que le Capitaine Jayden venait de hisser ses voiles de nuages, deux éclats de lumière jaillirent de l'eau. <em>Plouf ! Plouf !</em> C'étaient ses deux dauphins argentés — mais cette fois, ils ne venaient pas pour jouer. Ils nageaient vite, très vite, en faisant de grands cercles autour de la coque.\n\n— « Capitaine Jayden ! » sifflèrent-ils, tout essoufflés. « Ce soir, le vent souffle vers le Nord. C'est le moment ou jamais d'aller chercher le plus grand des trésors ! »\n\n— « Quel trésor ? » demanda Jayden en souriant.\n\n— « Le Trésor de l'Île aux Nuages ! » répondirent les dauphins en plongeant ensemble. « On raconte qu'il brille plus que mille pièces d'or. Mais attention, Capitaine… le terrible Barbe-Noire et ses pirates grincheux sont déjà en route ! »" },
          { img: "images/jayden_t1c1p2.jpg",
            text: "Jayden hocha la tête, très calme. Il n'avait pas peur : il savait que la ruse et la gentillesse sont les plus fortes de toutes les magies.\n\nIl vérifia son cap sur les étoiles, but une gorgée de son eau de nuage — celle qui donne une patience infinie — et tourna la barre vers le Nord. La brise tiède s'engouffra dans les voiles, et le navire glissa en silence sur l'eau tranquille, guidé par le sillage doré des deux dauphins.\n\nAu-dessus de lui, le ciel était rempli d'étoiles filantes, comme si la nuit elle-même lui souhaitait bon voyage.\n\n— « À nous deux, mystérieux trésor », murmura le Capitaine Jayden." },
        ]},
        { title: "Les Pirates Grincheux de l'Océan Noir", pages: [
          { img: "images/jayden_t1c2p1.jpg",
            text: "Pendant ce temps, à quelques milles de là, un autre bateau naviguait. C'était un immense galion noir, avec des voiles déchirées et une vieille coque qui grinçait à chaque vague : <em>criiic… crooc…</em>\n\nÀ son bord vivaient le Capitaine Barbe-Noire et son équipage de pirates méchants… ou plutôt, de pirates très, très grincheux. Car ces pirates-là avaient un gros problème : ils ne savaient pas comment s'endormir. Ils passaient leurs nuits à crier, à taper des pieds avec leurs grosses bottes, et à compter leurs pièces d'or pour essayer d'être heureux. Mais cela ne marchait jamais.\n\nAlors ils étaient épuisés, ils avaient de grands cernes violets sous les yeux, et cela les rendait grognons du matin au soir." },
          { img: "images/jayden_t1c2p2.jpg",
            text: "— « Tonnerre de Brest ! » hurlait Barbe-Noire en secouant sa boussole. « Je veux ce trésor ! On dit qu'il brille plus que mille pièces d'or ! Déployez les voiles noires, bande de moussaillons endormis ! Nous devons arriver avant le petit Jayden ! »\n\nLes pirates obéissaient en rouspétant. Ils n'aimaient pas la nuit, ils n'aimaient pas l'océan, et ils n'aimaient surtout pas faire de cadeaux.\n\nLe gros galion noir avançait en faisant un vacarme épouvantable, brisant les vagues calmes et faisant fuir les petits poissons lumineux, qui filaient se cacher tout au fond de l'eau." },
        ]},
        { title: "La Course dans la Brume Argentée", pages: [
          { img: "images/jayden_t1c3p1.jpg",
            text: "Le voyage était long. Jayden naviguait depuis des heures, guidé par le sillage doré de ses dauphins, quand une grande brume argentée se leva sur l'océan. Une brume magique, épaisse comme du coton : on n'y voyait plus rien à trois pas. C'était elle qui protégeait l'entrée de l'Île aux Nuages.\n\nDerrière lui, Jayden entendit des éclats de voix. Le galion des pirates entrait lui aussi dans la brume ! Mais comme les pirates criaient tous en même temps et fonçaient au hasard, ils se mirent à tourner en rond. <em>Bim ! Bam !</em> Le gros bateau noir frôla un rocher pointu.\n\n— « À l'aide ! On va couler ! » cria un pirate qui avait peur de l'eau." },
          { img: "images/jayden_t1c3p2.jpg",
            text: "En entendant cela, le Capitaine Jayden sentit son cœur se serrer. Son papa lui avait appris une règle très importante : <em>« Mets-toi d'abord à la place des autres, pour comprendre ce qu'ils ressentent. »</em>\n\nJayden réfléchit. Ces pirates étaient méchants… mais peut-être qu'ils étaient surtout perdus, effrayés, et terriblement fatigués.\n\nAlors il prit sa grande lanterne magique, celle qui brillait comme une petite lune, et l'alluma de toutes ses forces.\n\n— « Suivez ma lumière ! » lança-t-il d'une voix claire et rassurante. « Suivez les dauphins, ils vous guideront hors du danger ! »\n\nSur le galion, Barbe-Noire resta bouche bée. Personne, jamais, n'avait été gentil avec lui. Il ordonna à ses hommes de se taire, et le grand bateau noir suivit sagement la douce lueur dorée à travers la brume, pas à pas, vague après vague." },
        ]},
        { title: "La Découverte de l'Île aux Nuages", pages: [
          { img: "images/jayden_t1c4p1.jpg",
            text: "La brume finit par se dissiper, et les deux navires arrivèrent en même temps dans une baie abritée. Devant eux se dressait l'Île aux Nuages.\n\nC'était un endroit merveilleux. Les plages étaient faites d'un sable rose aussi doux que du velours. Les palmiers chantaient sous la brise, et tout en haut de la plus haute colline scintillait un immense coffre en nacre, qui brillait de toutes les couleurs de l'arc-en-ciel.\n\n— « Le trésor ! » hurla Barbe-Noire.\n\nLes pirates sautèrent de leur bateau et coururent sur la plage en se bousculant. Le Capitaine Jayden descendit lui aussi, mais lui marchait tranquillement sur le sable rose, accompagné de ses deux dauphins qui restaient tout près du bord." },
          { img: "images/jayden_t1c4p2.jpg",
            text: "Arrivé devant le grand coffre, Barbe-Noire poussa Jayden un peu brusquement et souleva le couvercle en grand.\n\n— « À moi le trésor ! » s'écria-t-il.\n\nMais à l'intérieur… il n'y avait ni pièces d'or, ni diamants, ni bijoux. Il y avait des dizaines de petits oreillers faits en plumes de nuages, des couvertures tissées en fils de lune, et une jolie fontaine magique qui répandait une douce odeur de fleur d'oranger et de lavande.\n\n— « Quoi ?! C'est ça, le trésor ? » grogna Barbe-Noire, déçu et furieux. « Des oreillers ? Quelle arnaque ! »" },
        ]},
        { title: "La Magie de la Gentillesse", pages: [
          { img: "images/jayden_t1c5p1.jpg",
            text: "Le Capitaine Jayden s'approcha doucement. Il prit un des oreillers de nuage — l'oreiller flottait presque tout seul dans ses mains, léger comme un soupir — et le tendit au gros pirate grincheux.\n\n— « Ce n'est pas un trésor pour acheter des choses », dit Jayden. « C'est le Trésor du Sommeil Paisible. Vous êtes en colère parce que vous ne dormez jamais. Essayez, vous verrez. »\n\nBarbe-Noire regarda Jayden, puis le petit oreiller. Il était si fatigué que ses jambes tremblaient sous lui. Alors il s'assit lourdement sur le sable rose, posa sa grosse tête sur l'oreiller magique, et s'enveloppa dans la couverture de lune que Jayden lui offrait." },
          { img: "images/jayden_t1c5p2.jpg",
            text: "En un instant, la magie de l'île opéra. La colère du pirate s'envola comme une petite fumée. L'odeur de lavande lui caressa le nez. Pour la première fois de sa vie, Barbe-Noire se sentit bien, en sécurité, et profondément calme.\n\nLes autres pirates firent comme leur capitaine. Ils prirent chacun un oreiller et s'allongèrent sur le sable tiède. Leurs visages durs devinrent tout doux. Et ils comprirent quelque chose de très important : le plus beau des trésors, ce n'est pas l'or. C'est la paix, l'amitié, et une bonne nuit de sommeil.\n\n— « Merci, Capitaine Jayden… » murmura Barbe-Noire en bâillant à s'en décrocher la mâchoire. « Tu es le plus grand des capitaines. On ne sera plus jamais méchants… promis… »" },
        ]},
        { title: "La Nuit des Gardiens de la Mer", pages: [
          { img: "images/jayden_t1c6p1.jpg",
            text: "Le calme le plus complet s'installa sur l'île. Les deux dauphins chantaient une douce mélodie depuis la mer turquoise. Le grand galion noir et le beau navire de Jayden étaient amarrés côte à côte, et se balançaient au même rythme, comme deux vieux amis.\n\nLes pirates s'endormirent les uns après les autres, en souriant dans leurs rêves. Cette nuit-là, sur la plage de sable rose, ils cessèrent pour toujours d'être les pirates les plus méchants de l'océan… et devinrent les plus gentils." },
          { img: "images/jayden_t1c6p2.jpg",
            text: "Le Capitaine Jayden remonta sur son pont. Il s'installa sur ses coussins tout doux, fatigué par ce long et magnifique voyage. Il regarda les étoiles qui brillaient au-dessus de lui, prit une grande inspiration de l'air parfumé de l'île, et ferma les yeux à son tour.\n\nIl savait que demain, de nouvelles aventures l'attendaient. Mais ce soir, tout le monde était heureux, apaisé, et bien au chaud.\n\nL'histoire est finie pour ce soir, Jayden. Le grand voyage est terminé, les dauphins dorment sous l'eau, les pirates devenus gentils protègent ton sommeil, et ton lit est le plus doux des navires. Ferme les yeux… et passe une très belle nuit." },
        ]},
      ]
    },
    {
      id: "t2", title: "Tome 2 — La Boussole des Étoiles Perdues", available: true,
      chapters: [
        { title: "Le Réveil des Nouveaux Gardiens", pages: [
          { img: "images/jayden_t2c1p1.jpg",
            text: "Le soleil ne s'était pas encore levé sur l'Île aux Nuages, mais le ciel commençait à se teinter d'un joli rose et d'un violet tout doux. Sur la plage de sable rose, un ronflement sonore faisait trembler les feuilles d'un palmier.\n\n<em>Pchhh-ronzzz… Pchhh-ronzzz…</em>\n\nC'était le Capitaine Barbe-Noire. Pour la première fois de sa vie, il avait dormi toute la nuit sans faire un seul cauchemar, la tête bien calée sur son oreiller de nuage. En ouvrant les yeux, il ne se sentait plus du tout grincheux. Il se sentait… en pleine forme. Et surtout, très gentil !\n\nIl courut vers le bord de l'eau et appela le bateau d'étoiles :\n\n— « Ohé, Capitaine Jayden ! Réveille-toi ! Viens voir ce que les vagues ont apporté sur la plage pendant qu'on dormait ! »" },
          { img: "images/jayden_t2c1p2.jpg",
            text: "Jayden, qui venait de se réveiller en buvant un grand verre de son eau de nuage, descendit l'échelle de corde. Ses deux fidèles dauphins l'attendaient déjà au bord, en faisant de petits bruits inquiets.\n\nAu milieu du sable rose, à moitié cachée par un joli coquillage, se trouvait une drôle de boussole en or blanc. Mais ses aiguilles ne tournaient pas comme celles d'une boussole ordinaire : elles étaient faites de pure lumière bleue, et elles pointaient droit vers le ciel étoilé, qui s'effaçait doucement dans le petit matin.\n\n— « Ça alors… » murmura Jayden. « Je n'ai jamais rien vu de pareil. »" },
        ]},
        { title: "La Mission Secrète", pages: [
          { img: "images/jayden_t2c2p1.jpg",
            text: "Jayden ramassa la boussole magique. Dès qu'il la prit dans sa main, une petite voix douce comme un chant de sirène s'en échappa :\n\n— <em>« Voyageur de la nuit, écoute le vent… Trois petites étoiles sont tombées dans l'océan. Si personne ne les retrouve avant le grand jour, elles s'éteindront pour toujours. »</em>\n\nBarbe-Noire ouvrit de grands yeux ronds, sa grosse barbe noire tremblant d'émotion :\n\n— « Par tous les bigorneaux ! Des étoiles en danger ? Capitaine Jayden, nous devons les sauver ! Mon grand galion et ton navire de nuages vont faire équipe ! »" },
          { img: "images/jayden_t2c2p2.jpg",
            text: "Jayden accepta tout de suite. Les pirates, devenus les Gardiens de la Mer, grimpèrent sur leur grand galion. Ils n'avaient plus leurs visages sombres d'autrefois : ils chantaient des chansons joyeuses en hissant des voiles toutes propres, qu'ils avaient recousues et lavées au petit matin.\n\n— « En avant ! » lança le Capitaine Jayden en tournant la barre.\n\nLa boussole magique projeta un grand rayon de lumière bleue sur l'eau tranquille pour leur indiquer le chemin. Les deux dauphins prirent la tête de la course, glissant comme des éclairs argentés pour ouvrir la voie. La grande mission de sauvetage était lancée !" },
        ]},
        { title: "La Première Étoile et les Poissons-Lanternes", pages: [
          { img: "images/jayden_t2c3p1.jpg",
            text: "La boussole les guida d'abord vers une grande barrière de corail mystérieuse. L'eau y était si transparente qu'on pouvait voir le fond de la mer, même à l'endroit le plus profond.\n\n— « Regardez là-dessous ! » cria un pirate depuis le haut du grand mât.\n\nTout au fond, coincée entre deux gros coraux violets, une petite étoile bleue clignotait faiblement. Elle avait très froid, toute seule dans l'eau profonde.\n\nJayden lança aussitôt une de ses inventions : un grand filet tissé en fils de lune, qui descendit tout doucement dans l'eau, sans faire une seule bulle. Mais les coraux étaient trop serrés. Impossible d'atteindre l'étoile !" },
          { img: "images/jayden_t2c3p2.jpg",
            text: "C'est alors que les dauphins eurent une idée. Ils plongèrent et appelèrent une bande de petits poissons-lanternes, ces poissons minuscules qui portent chacun une petite lumière dorée au bout du nez.\n\nEnsemble, les poissons se rassemblèrent autour des coraux et brillèrent de toutes leurs forces. Et là, il se passa quelque chose de magique : les coraux, ravis de recevoir tant de lumière, s'ouvrirent doucement comme des fleurs au soleil.\n\nLe filet de Jayden put attraper délicatement la première étoile et la remonter sur le pont. Dès qu'elle toucha le bois du bateau, elle se remit à briller d'une douce chaleur bleue. Tous les pirates applaudirent… en chuchotant, pour ne pas l'effrayer." },
        ]},
        { title: "La Deuxième Étoile dans la Grotte aux Échos", pages: [
          { img: "images/jayden_t2c4p1.jpg",
            text: "La boussole tourna ensuite ses aiguilles de lumière vers une immense falaise de pierre noire. Au milieu de la falaise s'ouvrait une grotte sombre, où le vent s'engouffrait en faisant des bruits un peu effrayants : <em>Ouuuh-ouuuh…</em>\n\nLes pirates méchants d'autrefois auraient eu bien trop peur d'y entrer. Mais les nouveaux pirates gentils étaient devenus très courageux. Barbe-Noire attrapa sa grande lanterne :\n\n— « Ne t'inquiète pas, Jayden. Celle-ci, c'est pour moi et mes hommes ! »\n\nEt ils ramèrent à bord d'une petite barque, droit vers l'intérieur de la grotte." },
          { img: "images/jayden_t2c4p2.jpg",
            text: "Tout au fond, posée sur une roche mouillée, la deuxième étoile — une étoile verte — pleurait de petites larmes de lumière. Le ciel lui manquait terriblement.\n\nLes pirates s'approchèrent tout doucement. Pour la rassurer, ils ne crièrent pas. Au contraire : ils se mirent à chanter la plus douce des berceuses de marins, celle que Jayden leur avait apprise. La grotte répéta la mélodie en écho, encore et encore, transformant l'endroit sombre en une magnifique boîte à musique.\n\nRassurée par cette gentille chanson, la petite étoile verte sécha ses larmes… et sauta d'elle-même dans les grands bras de Barbe-Noire, qui la ramena précieusement sur le navire, blottie contre sa barbe.\n\nPlus qu'une !" },
        ]},
        { title: "Le Grand Saut vers le Ciel", pages: [
          { img: "images/jayden_t2c5p1.jpg",
            text: "Le soleil commençait à pointer le bout de son nez à l'horizon. Il ne restait que quelques minutes avant que les étoiles perdues ne s'éteignent pour toujours !\n\nLa boussole s'affola, et ses aiguilles de lumière pointèrent le sommet d'une vague immense, dressée au beau milieu de l'océan comme une montagne d'eau. Tout en haut de cette vague, la troisième étoile — une grande étoile dorée — attendait, épuisée.\n\n— « On n'aura jamais le temps d'y arriver en bateau ! » s'inquiéta Barbe-Noire." },
          { img: "images/jayden_t2c5p2.jpg",
            text: "Le Capitaine Jayden réfléchit à toute vitesse. Soudain, il eut une idée : sa machine à nuages ! Il courut sur le pont et détacha la grande voile en forme de cerf-volant.\n\n— « Accrochez-vous ! » cria-t-il en la lançant dans le vent tiède.\n\nLa voile se gonfla d'un coup, immense, et souleva le navire tout entier au-dessus des vagues. Le bateau volait ! Il glissait dans les airs comme sur un toboggan de vent, pendant que les deux dauphins faisaient des bonds gigantesques pour encourager leur capitaine.\n\n<em>Fiiiiiouuuu !</em> Le navire magique passa juste au-dessus de la vague géante. Jayden se pencha, tendit sa main courageuse… et attrapa la dernière étoile dorée, juste à l'instant précis où le premier rayon de soleil touchait l'océan." },
        ]},
        { title: "Le Retour des Étoiles", pages: [
          { img: "images/jayden_t2c6p1.jpg",
            text: "Le navire redescendit tout doucement sur l'eau calme, à côté du galion. Jayden posa les trois petites étoiles — la bleue, la verte et la dorée — sur le pont, et leur versa quelques gouttes de son eau sucrée magique pour leur redonner des forces.\n\nLes trois étoiles se mirent à briller ensemble, de plus en plus fort. Puis, dans un joyeux bruissement de paillettes, elles s'envolèrent très haut dans le ciel du matin, laissant derrière elles des traînées de lumière multicolore. Elles avaient retrouvé leur maison, tout là-haut.\n\nAvant de disparaître, elles firent un dernier clin d'œil lumineux au Capitaine Jayden et à Barbe-Noire, pour leur dire merci." },
          { img: "images/jayden_t2c6p2.jpg",
            text: "Mais quelle nuit ! Les Gardiens de la Mer avaient veillé jusqu'au matin pour sauver les étoiles. Alors ils rentrèrent tout doucement à l'Île aux Nuages, dans la belle lumière rose du petit jour.\n\nEt il se passa alors quelque chose de merveilleux. D'habitude, ce sont les étoiles qui veillent sur les marins endormis. Mais ce matin-là, ce fut le contraire : de tout là-haut, invisibles dans le ciel bleu, les trois petites étoiles se mirent à chanter une berceuse rien que pour ceux qui les avaient sauvées. Les dauphins tirèrent de grands rideaux de brume douce autour des bateaux, comme on tire les rideaux d'une chambre.\n\nEt tout l'équipage, bâillant de bonheur, s'endormit pour la plus belle sieste de toute sa vie.\n\nToi aussi, tu as bien travaillé aujourd'hui, Jayden. Les trois petites étoiles te regardent de là-haut, même quand on ne les voit pas. Ferme les yeux, capitaine… elles chantent aussi pour toi. Bonne nuit." },
        ]},
      ]
    },
    {
      id: "t3", title: "Tome 3 — Le Chant du Coquillage de Lune", available: true,
      chapters: [
        { title: "Une Invitation Mystérieuse", pages: [
          { img: "images/jayden_t3c1p1.jpg",
            text: "Après le sauvetage des trois petites étoiles, une grande paix était revenue sur l'Océan des Rêves. Le soleil venait de se coucher, laissant place à une nuit d'un bleu profond. Le Capitaine Jayden et son ami Barbe-Noire s'étaient installés sur le pont du navire magique pour boire un verre d'eau de nuage bien fraîche, en se racontant leurs exploits.\n\nSoudain, un chant très doux s'éleva du fond de l'eau. Ce n'était pas un chant ordinaire : on aurait dit une mélodie jouée par une harpe de cristal.\n\n<em>Mmm-aaa-ooo…</em>\n\n— « Tu entends ça ? » chuchota Barbe-Noire, la main en cornet derrière l'oreille." },
          { img: "images/jayden_t3c1p2.jpg",
            text: "<em>Plouf !</em> Les deux dauphins argentés jaillirent de l'eau. Mais cette fois, ils ne jouaient pas : ils portaient délicatement, en équilibre sur leur nez, un immense coquillage d'un blanc de nacre, qui brillait comme la lune… mais d'une lumière toute pâle, qui tremblotait.\n\n— « Capitaine Jayden ! Capitaine Barbe-Noire ! » sifflèrent les dauphins. « Le Grand Coquillage de Lune s'est éteint à cause d'un gros chagrin. C'est lui qui joue la musique de l'océan ! Sans sa mélodie, les vagues vont s'arrêter de danser, et toute la mer va devenir triste. Il faut nous aider à retrouver son sourire ! »\n\nLes deux capitaines se regardèrent. Il n'y avait pas une seconde à perdre." },
        ]},
        { title: "La Carte des Bulles Brillantes", pages: [
          { img: "images/jayden_t3c2p1.jpg",
            text: "Jayden s'approcha et posa doucement sa main sur le coquillage. Aussitôt, le coquillage libéra une multitude de petites bulles brillantes, qui montèrent dans l'air de la nuit. Et là, sous les yeux émerveillés de tout l'équipage, les bulles se rassemblèrent… et dessinèrent une carte lumineuse, flottant juste au-dessus du pont !\n\n— « Regardez ! » dit Jayden en suivant le chemin du doigt. « Les bulles nous montrent la route jusqu'à la Baie des Coraux Chanteurs. C'est là-bas que nous trouverons le secret pour consoler le coquillage. »" },
          { img: "images/jayden_t3c2p2.jpg",
            text: "Barbe-Noire frappa dans ses grandes mains avec enthousiasme :\n\n— « Par tous les coquillages ! Équipage, parez à virer ! Suivons la carte magique ! »\n\nLes deux navires — le bateau aux voiles de nuages et le grand galion — se mirent en route côte à côte. La carte de bulles flottait juste devant la proue, éclairant l'océan d'une douce lumière tamisée, tandis que les dauphins nageaient en dessous pour vérifier que le chemin était sûr.\n\nSur le pont, bien installé au milieu des coussins, le Grand Coquillage de Lune se laissait porter. De temps en temps, il soupirait une petite note triste. « Tiens bon », lui murmurait Jayden. « On va le réparer, ton grand chagrin. »" },
        ]},
        { title: "La Tempête de Plumes de Brume", pages: [
          { img: "images/jayden_t3c3p1.jpg",
            text: "Alors qu'ils approchaient de la baie, le ciel changea. Ce n'était pas une tempête de pluie ni de vent méchant : c'était une tempête de plumes de brume. De grands nuages doux comme des plumes d'oie descendirent du ciel et enveloppèrent les deux navires. On n'y voyait plus rien du tout, et les bateaux commencèrent à s'éloigner l'un de l'autre sans le vouloir.\n\n— « Jayden ! Je ne te vois plus ! » cria Barbe-Noire depuis son galion, d'une voix un peu inquiète." },
          { img: "images/jayden_t3c3p2.jpg",
            text: "Jayden ne paniqua pas. Il se souvint de sa fidèle machine à nuages ! Il tourna la petite manivelle dorée et activa l'aspirateur de brume. <em>Vroumm-chuuut…</em> La machine aspira doucement toutes les plumes de brume… et les transforma en d'énormes coussins moelleux, qui tombèrent en pile sur le pont.\n\nLe chemin était à nouveau dégagé ! Et comme Jayden pensait toujours aux autres, il lança un des coussins géants sur le pont du galion.\n\nLes pirates s'assirent dessus pour ramer — et ils étaient si confortablement installés qu'ils se mirent à ramer avec une douceur et une régularité parfaites, comme une équipe de champions du calme." },
        ]},
        { title: "Le Secret des Coraux Chanteurs", pages: [
          { img: "images/jayden_t3c4p1.jpg",
            text: "Les navires entrèrent enfin dans la Baie des Coraux Chanteurs. C'était un endroit extraordinaire : sous l'eau claire, les coraux s'étiraient vers la surface comme de petites notes de musique colorées — des rondes roses, des croches orange, des soupirs violets.\n\nJayden descendit le Grand Coquillage de Lune et le plongea délicatement dans l'eau de la baie.\n\nÀ ce moment-là, tous les coraux se mirent à vibrer doucement, et à murmurer ensemble le secret :\n\n— <em>« Pour consoler le Coquillage de Lune, il ne faut ni or ni argent… Il a juste besoin d'entendre le rire d'un enfant, et une histoire partagée avec un ami de toujours. »</em>" },
          { img: "images/jayden_t3c4p2.jpg",
            text: "Jayden regarda Barbe-Noire. Barbe-Noire regarda Jayden. Un rire d'enfant… et une histoire entre amis ? Les deux capitaines comprirent tout de suite ce qu'ils devaient faire.\n\nIls s'assirent au bord du pont, les pieds ballants au-dessus de l'eau tiède, juste à côté du coquillage. Les deux dauphins sortirent la tête de l'eau pour écouter, et même les coraux semblèrent se pencher un peu.\n\n— « Une histoire drôle, hein… » dit Jayden avec un sourire malicieux. « J'en connais une. Tu es prêt, Barbe-Noire ? »" },
        ]},
        { title: "Le Rire Magique", pages: [
          { img: "images/jayden_t3c5p1.jpg",
            text: "Alors Jayden commença à raconter l'histoire d'une baleine magique qui avait le hoquet. Une baleine énorme, qui, à chaque fois qu'elle essayait de chanter, faisait <em>— hips ! —</em> et recrachait des bulles de savon multicolores par son évent. Et plus elle était gênée, plus elle hoquetait, et plus l'océan se remplissait de bulles arc-en-ciel qui éclataient sur le nez des poissons étonnés.\n\nL'histoire était si rigolote que Barbe-Noire éclata d'un rire énorme : « HA HA HA ! » Un rire de géant, qui fit onduler sa grande barbe noire.\n\nEt Jayden se mit à rire aussi — un rire pur, doux et cristallin, qui résonna dans toute la baie comme des clochettes." },
          { img: "images/jayden_t3c5p2.jpg",
            text: "Dès que les éclats de rire touchèrent l'eau, le Grand Coquillage de Lune absorba toute cette joie, comme une éponge boit l'eau.\n\nSa nacre blanche se mit à briller — rose, puis dorée, puis turquoise — de plus en plus fort, jusqu'à devenir absolument magnifique. Son gros chagrin s'était envolé !\n\nEt alors, il recommença à jouer sa douce mélodie de harpe de cristal. Encore plus belle qu'avant. Car une musique qui a connu le chagrin et retrouvé la joie est toujours un petit peu plus belle que les autres." },
        ]},
        { title: "Le Sommeil de l'Océan", pages: [
          { img: "images/jayden_t3c6p1.jpg",
            text: "Grâce au Capitaine Jayden et à Barbe-Noire, la musique magique de l'océan était revenue. Les vagues se remirent à bercer les bateaux sur un rythme calme et régulier, comme le tic-tac tranquille d'une horloge endormie. Les petits poissons lumineux revinrent danser en farandole autour des dauphins, qui traçaient des cercles de paix dans l'eau.\n\nEt le Grand Coquillage de Lune, désormais heureux, projetait vers le ciel une douce veilleuse scintillante qui éclairait toute la baie." },
          { img: "images/jayden_t3c6p2.jpg",
            text: "Fatigués par cette jolie quête, Jayden et Barbe-Noire s'allongèrent sur les gros coussins de brume magique. Les pirates s'endormirent en souriant, bercés par le chant du coquillage. Même les coraux baissèrent leurs couleurs, comme on baisse une lampe.\n\nVoilà, Jayden, la belle quête est terminée. Le coquillage chante sa berceuse rien que pour toi, les dauphins dorment sagement, et les pirates veillent sur la baie. Ferme tes yeux pleins de magie… ton lit est le plus sûr des navires. Bonne nuit, capitaine." },
        ]},
      ]
    },
    {
      id: "t4", title: "Tome 4 — L'Île aux Mille Chansons", available: false,
      chapters: [
        { title: "Le Palais de Corail", pages: [
          { img: "images/jayden_t4c1p1.jpg",
            text: "Le lendemain soir, le Grand Coquillage de Lune chantait si joyeusement que les deux navires naviguaient comme portés par un rêve. « Suivez ma musique », semblait-il dire. « J'ai une dernière merveille à vous montrer. »\n\nEt une île émergea de la brume dorée : l'Île aux Mille Chansons. Ses rochers étaient faits de cristal, et chacun vibrait doucement en jouant une note différente. Au centre se dressait un magnifique palais de coraux scintillants, fermé par une immense porte de corail, muette et silencieuse.\n\nJayden approcha le Grand Coquillage de Lune de la porte. Dès que sa musique de harpe toucha le corail, les notes s'allumèrent une par une… et la porte s'ouvrit en douceur.\n\nÀ l'intérieur, point de coffres d'or. Il y avait des centaines d'instruments de musique venus de la mer : des flûtes de nacre, des tambours de coquillages géants, des harpes de corail tissées de fils de lune. Et au milieu, une fontaine magique qui créait des bulles lumineuses — et dans chaque bulle vivait un souvenir : une histoire partagée, une amitié scellée, un rire sincère." },
          { img: "images/jayden_t4c1p2.jpg",
            text: "En voyant tant de merveilles, Barbe-Noire sentit un vieux picotement dans son cœur. C'était la cupidité — l'envie de tout prendre pour soi — qui essayait de revenir.\n\n— « Regardez tout ça ! » s'écria-t-il, les yeux brillants. « Nous pourrions tout emporter, tout vendre, et devenir les pirates les plus riches du monde ! »\n\nJayden posa doucement sa main sur le bras de son ami.\n\n— « Barbe-Noire… tu te souviens du secret des Coraux Chanteurs ? Ni or, ni argent. Un rire, et une histoire entre amis. Le vrai trésor, c'est tout ce que nous avons vécu ensemble. »\n\nBarbe-Noire regarda Jayden, puis la fontaine où dansaient les bulles de souvenirs — et dans l'une d'elles, il se vit lui-même, endormi pour la première fois sur le sable rose. Le picotement s'envola pour de bon. Il posa sa grande main sur l'épaule de Jayden :\n\n— « Tu as raison, petit capitaine. Pardonne-moi. Notre trésor, il est déjà là. »" },
        ]},
        { title: "Le Concert du Soir", pages: [
          { img: "images/jayden_t4c2p1.jpg",
            text: "Dès que Barbe-Noire eut prononcé ces mots, l'île tout entière s'illumina, comme pour dire merci. La fontaine s'activa, et des milliers de bulles pleines de rires et de chansons montèrent dans le ciel du soir.\n\nAlors, de tous les coins de l'Océan des Rêves, les créatures marines arrivèrent pour la grande fête. Les dauphins argentés furent rejoints par des baleines chantantes, des méduses lumineuses qui dansaient en rythme, et des bancs de poissons qui scintillaient comme des feux d'artifice sous l'eau.\n\nLe Capitaine Jayden choisit une flûte de nacre. Le Capitaine Barbe-Noire, avec un grand sourire, s'installa derrière une énorme harpe de corail. Et ensemble, guidés par la mélodie du Grand Coquillage de Lune, ils commencèrent à jouer." },
          { img: "images/jayden_t4c2p2.jpg",
            text: "Le concert fut d'abord joyeux et grandiose : l'océan entier vibrait de bonheur. Puis, à mesure que la nuit tombait et que les premières étoiles s'allumaient, la musique se fit de plus en plus douce.\n\nLes chansons joyeuses devinrent des berceuses. Les baleines chantèrent tout bas, de leur grosse voix de velours. Les méduses tamisèrent leur lumière, comme des lampions qu'on baisse à l'heure du coucher. Et la flûte de Jayden ne jouait plus que trois petites notes, légères comme des plumes, qui donnaient envie de fermer les yeux.\n\nUn à un, les petits poissons s'endormirent en scintillant faiblement. La grande fête de l'océan se transformait tout doucement en la plus belle des veillées." },
        ]},
        { title: "La Constellation de l'Amitié", pages: [
          { img: "images/jayden_t4c3p1.jpg",
            text: "Quand la dernière note s'éteignit, le Grand Coquillage de Lune, qui avait retrouvé toute sa joie, s'illumina une dernière fois. Il s'éleva doucement dans le ciel de la nuit, monta au milieu des étoiles… et devint une constellation toute neuve, en forme de coquillage : la Constellation de l'Amitié. Elle s'alluma au-dessus d'eux comme une veilleuse géante, pour veiller sur l'océan chaque nuit, pour toujours.\n\nMais avant de partir, le coquillage avait laissé tomber deux fragments de lumière.\n\nLe premier, un petit morceau de nacre brillante, flotta jusqu'à Jayden. — <em>« Pour toi, courageux capitaine. C'est la boussole des cœurs : elle t'indiquera toujours le chemin vers tes amis et vers la joie. »</em>\n\nLe deuxième, une petite flûte de coquillage ornée de fils de lune, flotta jusqu'à Barbe-Noire. — <em>« Et pour toi, grand gardien. Joue, et partage ta gentillesse avec le monde. »</em>" },
          { img: "images/jayden_t4c3p2.jpg",
            text: "Les deux capitaines se regardèrent en souriant. Ils n'étaient plus un vieux pirate et un jeune capitaine : ils étaient des amis inséparables, les deux gardiens de l'Océan des Rêves.\n\nIls amarrèrent leurs navires côte à côte, juste sous la nouvelle constellation. Chacun rejoignit ses coussins. L'océan tout entier respirait doucement, endormi dans la lumière nacrée.\n\n— « Où irons-nous demain, capitaine ? » murmura Barbe-Noire en bâillant.\n\n— « Vers de nouvelles histoires, Barbe-Noire. Vers de nouveaux rires », répondit Jayden en serrant son petit fragment de nacre. « Mais demain… Cette nuit, on dort. »\n\nEt voilà, Jayden. Le grand livre se referme pour ce soir. La Constellation de l'Amitié brille juste au-dessus de ton lit, la boussole des cœurs connaît le chemin de tes rêves, et tes deux capitaines préférés dorment déjà, côte à côte sur l'Océan des Rêves. Ferme les yeux, mon capitaine. Les étoiles veillent, les amis sont là, et demain t'attend une nouvelle aventure. Bonne nuit… et fais de beaux rêves." },
        ]},
      ]
    },
  ]
};
